[run]
sample = 'test'
ncores = 32
plot = false
overwrite = true
#gravity = ['GR', 'MG']

[profile]
rin = 0.1
rout = 3.0
njk = 100
nside = 64
addnoise = false
binning = 'lin' # 'lin' or 'log'

[lenses]
z_edges = [0.1, 0.2] # redshift edges to cut between
rv_edges = [10.0, 20.0]
voidtype = ['mixed'] # ['mixed', 'S', 'R']
# delta_edges = [-1.0, 10.0] # TODO: add the option to cut by delta values
flag = 2.0
# is_mice = false
fullshape = true

[lenses.gr]
name = 'etc.dat'

[lenses.mg]
name = 'etc.dat'

[lenses.columns]
rv = 1 # void radius
ra = 2
dec = 3
z = 4 #redshift
delta = 9 # integrated density between 2-3 Rv, for void classification

[sources]

[sources.gr]
name = 'etc.fits'

[sources.mg]
name = 'etc.fits'

[sources.columns]
# column names of source cat
ra = 'ra_gal'
dec = 'dec_gal'
redshift = 'redshift'
pix = 'pix'
kappa = 'kappa'
gamma1 = 'gamma1'
gamma2 = 'gamma2'
eps1 = 'eps1'
eps2 = 'eps2'

[randoms]
[randoms.gr]
name = 'etc.dat'

[randoms.mg]
name = 'etc.dat'

[cosmology]
h=1.0
Om0=0.25
Ode0=0.75
